spring.application.name=backend

# 1. The Address (Protocol : // Host : Port / DatabaseName)
spring.datasource.url=jdbc:postgresql://localhost:5432/socialdb

# 2. The Username (from our docker command)
spring.datasource.username=hamza

# 3. The Password (from our docker command)
spring.datasource.password=password

# 4. This tells Hibernate to create the tables for you automatically!
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
